# Generated by Django 6.0.4 on 2026-07-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphabetcity', '0002_resident_alter_answer_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='grant_writing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
