# Generated by Django 6.0.4 on 2026-07-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphabetcity', '0003_resident_grant_writing_alter_answer_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='grant_writing',
        ),
        migrations.AddField(
            model_name='answer',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
